### ISSUE TITLE
enhance add_components capabilities 

### ISSUE THREAD

**Issue by jd-lara** [NREL/InfrastructureSystems.jl#13]
allow to run `add_components` and take as an argument and iterator of components.

**Comment by daniel-thom** [comment]
I'm not completely opposed to this proposal.  However, I think that creating too many functions can make it difficult for users to find what they want.  Julia already provides tools to solve this problem with our add_component function. For consideration, we could document this as an example in the add_component docstring:

```
buses = [bus1, bus2, bus3]
generators = [gen1, gen2, gen3]
foreach(x -> add_component!(sys, x), Iterators.flatten((buses, generators)))
```

What do you think?

**Comment by daniel-thom** [comment]
I will elaborate to emphasize the amount of method explosion that could occur.  Here is what currently happens with add_component!.

User calls add_component!(system, component).
The System performs some internal checks and then forwards the call to its data container.
The IS.SystemData forwards the call to its components container, which is where the real logic lives.

If we add a new function called add_components! then we have to also add the two levels of forwarding, as well as unit tests.  Any other package consuming InfrastructureSystems would also have to add the forwarding.  Doing this kind of thing with lots of methods can lead to a lot of bloat.  I think we will be better off if we keep our API as simple and small as possible.

**Comment by jd-lara** [comment]
The docstring solution is good enough.
