### ISSUE TITLE
Autogeneration code failing in < character

### ISSUE THREAD

**Issue by jd-lara** [NREL/InfrastructureSystems.jl#33]
see https://travis-ci.org/NREL/PowerSystems.jl/jobs/614313755#L348 

The characters `<:` are being rendered as `&lt`

**Comment by daniel-thom** [comment]
This can be fixed by wrapping the data_type in ```{{{data_type}}}``` instead ``{{data_type}}`` in src/utils/generate_structs.jl.  This must be the first time someone defined a data_type with <:
